all:
  children:
    server:
      hosts:
        ubuntu-nc:
          ansible_host: 10.0.10.45
        maria:
          ansible_host: 10.0.10.34
        onlyoffice:
          ansible_host: onlyoffice.home.local
        kuma:
          ansible_host: kuma.home.local
        adguard:
          ansible_host: 10.0.10.40
        adguard2:
          ansible_host: 10.0.10.41
        vpn:
          ansible_host: vpn.home.local
        ntfy:
          ansible_host: ntfy.home.local
        proxy:
          ansible_host: 173.255.238.150
        pve:
          ansible_host: 10.0.10.12
        ubuntu-docker:
          ansible_host: 10.0.10.42
