all:
  children:
    server:
      hosts:
        ubuntu-nc:
          ansible_host: 10.0.10.45
        maria:
          ansible_host: 10.0.10.34
        adguard:
          ansible_host: 10.0.10.40
        adguard2:
          ansible_host: 10.0.10.41
        proxy:
          ansible_host: 173.255.238.150
        pve:
          ansible_host: 10.0.10.12
        ubuntu-docker:
          ansible_host: 10.0.10.42
    workstations:
      hosts:
        thinkpad:
