# - name: notify healthchecks.io that the job ran
#   uri:
#     url: https://hc-ping.com/{{ healthcheck_uuid }}
#   changed_when: false
#   when: healthcheck_uuid is defined

- name: Send completion notification via Pushover
  tags: always
  script: >
    alert.py
    "Ansible Pull Success on {{ ansible_hostname }}"
    "Ansible-Pull"
    "0"
    "{{ pushover_user_key }}"
    "{{ pushover_app_token }}"
    "{{ pushover_device }}"
  args:
    executable: python3
  changed_when: false
  no_log: true

