- block:

    - name: Send failure notification via Pushover
      tags: always
      script: >
        alert.py
        "Task failed: {{ ansible_failed_task.name }}"
        "Ansible Pull Failed on {{ ansible_hostname }}"
        "1"
        "{{ pushover_user_key }}"
        "{{ pushover_app_token }}"
        "{{ pushover_device }}"
      args:
        executable: python3
      changed_when: false
      no_log: true

  rescue:

    - name: Send failure notification via Pushover (rescue)
      tags: always
      script: >
        alert.py
        "Ansible failed but task details unavailable"
        "Ansible Pull Failed on {{ ansible_hostname }}"
        "1"
        "{{ pushover_user_key }}"
        "{{ pushover_app_token }}"
        "{{ pushover_device }}"
      args:
        executable: python3
      changed_when: false
      no_log: true
